config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/admin', to: 'admin#index'
  post '/admin/create_rate', to: 'admin#create_rate'
  resources :sessions, only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cb_exchange_rate.rb
class CbExchangeRate < ApplicationRecord

  validates_presence_of :date, :rate
  validates_numericality_of :rate, greater_than: 0
  after_create :create_broadcast_job

  def self.stub_for_dev
    CbExchangeRate.create(date: Date.today, rate: 65)
  end

  def self.get_current_rate
    rate = ForcedRate.where('expires > ?', Time.now).last
    rate ||= CbExchangeRate.where(date: Date.today).last
    rate
  end

  def create_broadcast_job
    BroadcastWorker.perform_async
  end

end

app/models/forced_rate.rb
class ForcedRate < ApplicationRecord
  validates_presence_of :expires, :rate
  validates_numericality_of :rate, greater_than: 0

  after_create :create_broadcast_job

  def create_broadcast_job
    BroadcastWorker.perform_at(self.expires)
  end
end

app/models/site_user.rb
require 'digest/md5'
class SiteUser
  include ActiveModel::Model

  attr_accessor :username, :password

  def login_valid?
    username == Rails.application.credentials[:login] && Digest::MD5.hexdigest(password) == Rails.application.credentials[:password]
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authentication_required!

  def index
    @rate = ForcedRate.new
    @rates = ForcedRate.order(id: :desc).first(50)
  end

  def create_rate
    @rate = ForcedRate.create(forced_rate_params)
    # should be async, but whatever this is just a test app
    ActionCable.server.broadcast 'web_notifications_channel', rate: @rate.rate if @rate.expires > Time.now
  end

  private

  def forced_rate_params
    params.require(:forced_rate).require(:rate)
    params.require(:forced_rate).require(:expires)
    params.require(:forced_rate).permit(:rate, :expires)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ApplicationNotAuthenticated = Class.new(StandardError)

  rescue_from ApplicationNotAuthenticated do
    respond_to do |format|
      format.json {render json: {errors: [message: '401 Not Authorized']}, status: 401}
      format.html do
        flash[:notice] = 'Not Authorized to access this page, plese log in'
        redirect_to new_session_path
      end
      format.any {head 401}
    end
  end

  def authentication_required!
    session[:current_user] || raise(ApplicationNotAuthenticated)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rate = CbExchangeRate.get_current_rate
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @site_user = SiteUser.new
  end

  def create
    sleep 2 unless Rails.env.test?
    site_user_params = params.require(:site_user)
    @site_user = SiteUser.new
                     .tap { |su| su.username = site_user_params[:username] }
                     .tap { |su| su.password = site_user_params[:password] }

    if @site_user.login_valid?
      session[:current_user] = true
      redirect_to '/admin'
    else
      @site_user.password = nil
      flash[:notice] = 'Sorry, wrong credentils'
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_rate.html.erb
<tr class="<%= rate.expires > Time.now ? 'text-success' : '' %>">
  <td><%= rate.rate %></td>
  <td><%= rate.expires %></td>
</tr>

app/views/admin/create_rate.js.erb
$('#rates_history > tbody:last-child').prepend('<%= escape_javascript(render partial: 'rate', object: @rate) %>');

app/views/admin/index.html.erb
<%= form_for @rate, url: admin_create_rate_url, remote: true, html: {style: "width: 500px;"} do |f| %>
  <div class="card">
    <div class="card-header">
      Forced rate
    </div>
    <div class="card-body">
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <%= f.text_field :rate, class: 'form-control', required: true, placeholder: "Rate" %>
        </div>

        <div class="col-md-8 mb-3">
          <%= f.text_field :expires, class: 'form-control datepicker', required: true, placeholder: "Expires" %>
        </div>

      </div>
      <button type="submit" class="btn btn-primary">Submit form</button>
    </div>
  </div>
<% end %>

<table class="table mt-5" style="width: auto;" id="rates_history">
  <thead>
  <tr>
    <th scope="col">Rate</th>
    <th scope="col">Expires</th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: 'rate', collection: @rates %>
  </tbody>
</table>

<script>
    $(function () {
        $('.datepicker').datetimepicker({step: 1});
    });
</script>

app/views/home/index.html.erb
<div class="card" style="width: 500px">
  <div class="card-header">
    Actual rate
  </div>
  <div class="card-body" id="rate">
    <% if @rate %>
      <%= @rate.rate %>
    <% else %>
      There is no data :(
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtominvestTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="p-5">
    <%= yield %>
  </body>
</html>